In [1]:
from test_helpers2 import readData, run_fairTest, runSingleTest, TestResults
import pandas as pd

In [ ]:
dataInfo = {
    'file': 'data/default.csv',
    'groupCol': 'X2'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 10,
            'train_limit': 10,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'barrierCrossover',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'DefaultX2HEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [5, 15, 30]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [10, 15, 20]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)

{'price_limit': 10, 'train_limit': 10, 'fixed_model_params': {'ruleGenerator': 'Hybrid', 'masterSolver': 'barrierCrossover', 'numRulesToReturn': 100, 'fairness_module': 'HammingEqOdd'}, 'num_hp_splits': 3, 'name': 'DefaultX2HEO', 'hyper_paramaters': {'epsilon': [0.02, 1], 'ruleComplexity': [5, 15, 30]}}
2 parameters provided for hyper-parameter epsilon
3 parameters provided for hyper-parameter ruleComplexity
****** Running split 0 ******
**** Running Test DefaultX2HEO ****
Split 0
HammingEqOdd
Using Hybrid
Using license file /Users/connorlawless/gurobi.lic
Academic license - for non-commercial use only
Using barrier with default crossover
Changed value of parameter Method to 2
   Prev: -1  Min: -1  Max: 5  Default: -1
Solving Master
Master solving took 0.04 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Rule generation took 10.02 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule gene

   Prev: -1  Min: -1  Max: 5  Default: -1


/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Adding Rules
Rule model adding rules took 0.01 seconds
Adding columns took 3.16 seconds
Solving Master
Master solving took 0.07 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.02 seconds
Starting Rule generation
Hybrid using greedy
Hybrid using IP
No rules with reduced costs generated.
Rule generation took 10.34 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 10.36 seconds
Rule model adding rules took 0.02 seconds
Adding columns took 0.18 seconds
Time limit for column generation exceeded. Solving MIP.
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Number of solutions returned:  2
Solution: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

Results: (Acc) 0.780 (Time) 14 (Complex) 13 (Cols Gen) 17  (Num Iter) 1
{'accuracy': [0.783, 0.7804444444444445], 'accuracy_train': [0.7813333333333333, 0.7826111111111111], 'mip': [[3984.0], [3925.0]], 'mip_final': [3984.0, 3925.0], 'ip': [3947.0, 3925.0], 'complexity': [13.0, 13.0], 'eqOfOp': [], 'times': [13.322804298, 13.986538583], 'num_iter': [1, 1], 'num_cols_gen': [16, 17], 'hp': 'epsilon', 'hp_val': 0.02, 'mean_accuracy': 0.7817222222222222, 'std_accuracy': 0.0012777777777777666, 'mean_accuracy_train': 0.7819722222222223, 'std_accuracy_train': 0.000638888888888911, 'mean_mip_final': 3954.5, 'std_mip_final': 29.5, 'mean_ip': 3936.0, 'std_ip': 11.0, 'mean_complexity': 13.0, 'std_complexity': 0.0, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 13.6546714405, 'std_times': 0.33186714250000016, 'mean_num_iter': 1.0, 'std_num_iter': 0.0, 'mean_num_cols_gen': 16.5, 'std_num_cols_gen': 0.5}
Split 2
HammingEqOdd
Using Hybrid
Using barrier with default crossover
Changed value of pa

  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Results: (Acc) 0.782 (Time) 14 (Complex) 13 (Cols Gen) 17  (Num Iter) 1
{'accuracy': [0.783, 0.7804444444444445, 0.7822222222222223], 'accuracy_train': [0.7813333333333333, 0.7826111111111111, 0.7817222222222222], 'mip': [[3984.0], [3925.0], [3940.0]], 'mip_final': [3984.0, 3925.0, 3940.0], 'ip': [3947.0, 3925.0, 3940.0], 'complexity': [13.0, 13.0, 13.0], 'eqOfOp': [], 'times': [13.322804298, 13.986538583, 13.876019870999997], 'num_iter': [1, 1, 1], 'num_cols_gen': [16, 17, 17], 'hp': 'epsilon', 'hp_val': 0.02, 'mean_accuracy': 0.781888888888889, 'std_accuracy': 0.001069594746532854, 'mean_accuracy_train': 0.781888888888889, 'std_accuracy_train': 0.0005347973732664521, 'mean_mip_final': 3949.6666666666665, 'std_mip_final': 25.037749277618566, 'mean_ip': 3937.3333333333335, 'std_ip': 9.177266598624136, 'mean_complexity': 13.0, 'std_complexity': 0.0, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 13.728454250666665, 'std_times': 0.29

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.00 seconds
Adding columns took 1.26 seconds
Solving Master
Master solving took 0.04 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.02 seconds
Starting Rule generation
Hybrid using greedy
Hybrid using IP
No rules with reduced costs generated.
Rule generation took 8.75 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 8.77 seconds
Rule model adding rules took 0.02 seconds
Adding columns took 0.20 seconds
Solving Master
Master solving took 0.08 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.02 seconds
Starting Rule generation
Hybrid using IP
Rule generation took 0.56 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 0.58 seconds
Rule model adding rules took 0.00 seconds
Adding columns took 0.20 seconds
Solving Master
Master solving took 0.04 seconds
Starting Rule Generation
Star

Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7908333333333334
Best accuracy: 0.7918333333333333
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.

Results: (Acc) 0.781 (Time) 27 (Complex) 4 (Cols Gen) 53  (Num Iter) 2
{'accuracy': [0.7812222222222223, 0.781], 'accuracy_train': [0.7817777777777778, 0.7818333333333334], 'mip': [[3984.0, 3928.0], [3926.666666666666, 3926.666666666666]], 'mip_final': [3928.0, 3926.666666666666], 'ip': [3928.0, 3927.0], 'complexity': [3.0, 4.0], 'eqOfOp': [], 'times': [15.541448631999998, 26.877276428000002], 'num_iter': [2, 2], 'num_cols_gen': [27, 53], 'hp': 'ruleComplexity', 'hp_val': 5, 'mean_accuracy': 0.7811111111111111, 'std_accuracy': 0.00011111111111111738, 'mean_accuracy_train': 0.7818055555555556, 'std_accuracy_train': 2.7777777777793222e-05, 'mean_mip_final': 3927.333333333333, 'std_mip_final': 0.6666666666669698, 'mean_ip': 3927.5, 'std_ip': 0.5, 'mean_complexity': 3.5, 'std_complexity': 0.5, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 21.20936253, 'std_times': 5.667913898000002, 'mean_num_iter': 2.0, 'std_num_iter': 0.0, 'mean_num_cols_gen': 40.0, 'std_num_cols_gen': 13.0}
Split

Best accuracy: 0.7826111111111111
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Results: (

Best accuracy: 0.7810555555555555
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 

Results: (Acc) 0.780 (Time) 21 (Complex) 13 (Cols Gen) 55  (Num Iter) 2
{'accuracy': [0.7798888888888889, 0.7818888888888889, 0.7804444444444445], 'accuracy_train': [0.7826111111111111, 0.7810555555555555, 0.7818888888888889], 'mip': [[3984.0], [3945.0], [3927.0, 3927.0]], 'mip_final': [3984.0, 3945.0, 3927.0], 'ip': [3913.0, 3941.0, 3927.0], 'complexity': [2.0, 8.0, 13.0], 'eqOfOp': [], 'times': [15.673153686999996, 19.797704716999988, 20.728092667999988], 'num_iter': [1, 1, 2], 'num_cols_gen': [28, 48, 55], 'hp': 'ruleComplexity', 'hp_val': 15, 'mean_accuracy': 0.7807407407407408, 'std_accuracy': 0.0008429486427215494, 'mean_accuracy_train': 0.7818518518518518, 'std_accuracy_train': 0.0006355926778419061, 'mean_mip_final': 3952.0, 'std_mip_final': 23.790754506740637, 'mean_ip': 3927.0, 'std_ip': 11.430952132988164, 'mean_complexity': 7.666666666666667, 'std_complexity': 4.4969125210773475, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 18.732983690666657, 'std_times': 2.1967134

Split 2
HammingEqOdd
Using Hybrid
Using barrier with default crossover
Changed value of parameter Method to 2
   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.02 seconds
Adding columns took 7.14 seconds
Solving Master
Master solving took 0.03 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Rule generation took 8.37 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 8.38 seconds
Rule model adding rules took 0.01 seconds
Adding columns took 2.38 seconds
Time limit for column generation exceeded. Solving MIP.
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Number of solutions returned:  3
Solution: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.14 seconds
Adding columns took 69.77 seconds
done
Sorting RC/reset took 70.19 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 1.38 seconds
Number of solutions returned:  1
Solution: []
Accuracy:  0.7788148148148148
Best accuracy: 0.7788148148148148
Selected Rule set: []
Results: (Acc) 0.779 (Time) 134 (Complex) 0 (Cols Gen) 253  (Num Iter) 0
{'accuracy': [0.7786666666666666], 'accuracy_train': [0.7788148148148148], 'mip': [[]], 'mip_final': [-1], 'ip': [5972.0], 'complexity': [0.0], 'eqOfOp': [], 'times': [133.91519330399996], 'num_iter': [0], 'num_cols_gen': [253], 'accuracy_True': [0.7573467674223342], 'accuracy_False': [0.7927031509121062], 'eqOp_True': [0.0], 'eqOp_False': [0.0], 'eqOp_True_Train': [0.0], 'eqOp_False_Train': [0.0], 'accuracy_True_Train': [0.7584369449378331], 'accuracy_False_Train

Results: (Acc) 0.776 (Time) 344 (Complex) 19 (Cols Gen) 253  (Num Iter) 0
{'accuracy': [0.7763333333333333], 'accuracy_train': [0.7822962962962963], 'mip': [[]], 'mip_final': [-1], 'ip': [5891.0], 'complexity': [19.0], 'eqOfOp': [], 'times': [344.09763117800014], 'num_iter': [0], 'num_cols_gen': [253], 'accuracy_True': [0.7556675062972292], 'accuracy_False': [0.7899391929242675], 'eqOp_True': [0.01730103806228374], 'eqOp_False': [0.013333333333333334], 'eqOp_True_Train': [0.03908668730650155], 'eqOp_False_Train': [0.03512396694214876], 'accuracy_True_Train': [0.7633916051229317], 'accuracy_False_Train': [0.7947003618965834], 'mean_accuracy': 0.7763333333333333, 'std_accuracy': 0.0, 'mean_accuracy_train': 0.7822962962962963, 'std_accuracy_train': 0.0, 'mean_mip_final': -1.0, 'std_mip_final': 0.0, 'mean_ip': 5891.0, 'std_ip': 0.0, 'mean_complexity': 19.0, 'std_complexity': 0.0, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 344.09763117800014, 'std_times': 0.0, 'mean_num_iter': 0.0

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.15 seconds
Adding columns took 58.19 seconds
Solving relaxed (filter) master
Solving with 253 rules
Master solving took 0.12 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [134 121 135 132 206  28 122 138 145 133  60  66 128 118 143 129  24 110
 123 179 111 125 139  48 136   7  34  82  71  83  72  74  75  77  78  79
  80  84  81  70  76  73 124 149 144  45   6 151 150   9 200  29   8  92
 201  13  95  25  23  22 183  94 203 196 137 158 168  91  12  67  61  93
  14  96  97  98  19  17 204 226 231  46  21 225  37 224 229  16  26  27
   4 228 230  41 227 164  20  33 162  38 169 173  42 234 214 167 176 213
 155  64  44 154  11  63 147 246  43   0  47 140  49  50  55  58  51   2
 197 142 146 148 207  30  15 178  18 202 205 113 209 119 141   3 130   5
 199 116  52 126  59  65  69 220 166 157 212  62  68 112  40 115 114 210
 177 120 218 222  31 131 219 2

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.14 seconds
Adding columns took 59.10 seconds
Solving relaxed (filter) master
Solving with 253 rules
Master solving took 0.13 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [121  28 132 138  66 134  48  60 122 206 135 145 133 128 118  24 143 129
  45 123 110 179 125 111 136 139   7  72  84  83  82  81  70  80  78  77
  76  75  74  73  79  71  34 124 149  46   6 226 150 151 144 201   9   8
  22  23  25  92  94  29  13 183 203 200  95 231 196 137 158 168 229  91
  12 230  97  93  98  96  17 204  19  14 227  33 225  21  37   4  26  27
 228  16  11  41  61 164  67 119  20 130 162 169 207 173 116 224 234 205
 126 214 167  43 176 209  58  55  50  49 155 213  30  38 178 154  42   0
  47   2 197  51 246  64 120  15  44 131 210  18 202  52  63 117 113  65
  59 147 220 127  69   3 140   5 199 146 148 142 177 166 157 218 212 141
 222  62  68  31 219  32 112 1

Results: (Acc) 0.794 (Time) 122 (Complex) 8 (Cols Gen) 253  (Num Iter) 0
{'accuracy': [0.7943333333333333], 'accuracy_train': [0.792962962962963], 'mip': [[]], 'mip_final': [-1], 'ip': [5593.0], 'complexity': [8.0], 'eqOfOp': [], 'times': [121.58616997399986], 'num_iter': [0], 'num_cols_gen': [253], 'accuracy_True': [0.7766582703610412], 'accuracy_False': [0.8059701492537313], 'eqOp_True': [0.1522491349480969], 'eqOp_False': [0.12], 'eqOp_True_Train': [0.16253869969040247], 'eqOp_False_Train': [0.12957497048406139], 'accuracy_True_Train': [0.7771337758249977], 'accuracy_False_Train': [0.8033490768570202], 'mean_accuracy': 0.7943333333333333, 'std_accuracy': 0.0, 'mean_accuracy_train': 0.792962962962963, 'std_accuracy_train': 0.0, 'mean_mip_final': -1.0, 'std_mip_final': 0.0, 'mean_ip': 5593.0, 'std_ip': 0.0, 'mean_complexity': 8.0, 'std_complexity': 0.0, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 121.58616997399986, 'std_times': 0.0, 'mean_num_iter': 0.0, 'std_num_iter': 0.0,

Results: (Acc) 0.794 (Time) 123 (Complex) 13 (Cols Gen) 253  (Num Iter) 0
{'accuracy': [0.7936666666666666], 'accuracy_train': [0.7931851851851852], 'mip': [[]], 'mip_final': [-1], 'ip': [5587.0], 'complexity': [13.0], 'eqOfOp': [], 'times': [122.70567261399992], 'num_iter': [0], 'num_cols_gen': [253], 'accuracy_True': [0.7758186397984886], 'accuracy_False': [0.8054173576561636], 'eqOp_True': [0.1522491349480969], 'eqOp_False': [0.12], 'eqOp_True_Train': [0.16563467492260062], 'eqOp_False_Train': [0.13046044864226683], 'accuracy_True_Train': [0.7776011965971767], 'accuracy_False_Train': [0.8034104152609949], 'mean_accuracy': 0.7936666666666666, 'std_accuracy': 0.0, 'mean_accuracy_train': 0.7931851851851852, 'std_accuracy_train': 0.0, 'mean_mip_final': -1.0, 'std_mip_final': 0.0, 'mean_ip': 5587.0, 'std_ip': 0.0, 'mean_complexity': 13.0, 'std_complexity': 0.0, 'mean_eqOfOp': nan, 'std_eqOfOp': nan, 'mean_times': 122.70567261399992, 'std_times': 0.0, 'mean_num_iter': 0.0, 'std_num_iter':

Solution: []
Accuracy:  0.7788148148148148
Best accuracy: 0.792962962962963
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

In [ ]:
dataInfo = {
    'file': 'data/compas.csv',
    'groupCol': 'race'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 45,
            'train_limit': 300,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'Default',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'COMPASRaceHEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [5, 15, 30]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [10, 15, 20]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)

In [ ]:
dataInfo = {
    'file': 'data/adult.csv',
    'groupCol': 'gender'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 45,
            'train_limit': 300,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'barrierCrossover',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'AdultGenderHEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [60, 80, 100]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [60, 70, 80, 90, 100, 110]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)