In [1]:
from test_helpers2 import readData, run_fairTest, runSingleTest, TestResults
import pandas as pd

In [2]:
dataInfo = {
    'file': 'data/default.csv',
    'groupCol': 'X2'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 45,
            'train_limit': 300,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'barrierCrossover',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'DefaultX2HEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [5, 15, 30]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [10, 15, 20]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)

{'price_limit': 10, 'train_limit': 10, 'fixed_model_params': {'ruleGenerator': 'Hybrid', 'masterSolver': 'barrierCrossover', 'numRulesToReturn': 100, 'fairness_module': 'HammingEqOdd'}, 'num_hp_splits': 3, 'name': 'DefaultX2HEO', 'hyper_paramaters': {'epsilon': [0.02, 1], 'ruleComplexity': [5, 15, 30]}}
2 parameters provided for hyper-parameter epsilon
3 parameters provided for hyper-parameter ruleComplexity
****** Running split 0 ******
**** Running Test DefaultX2HEO ****
Hyper parameters for CV:  {'epsilon': [0.02, 1], 'ruleComplexity': [5, 15, 30]}
Split 0
HammingEqOdd
Using Hybrid
Using license file /Users/connorlawless/gurobi.lic
Academic license - for non-commercial use only
Using barrier with default crossover
Changed value of parameter Method to 2
   Prev: -1  Min: -1  Max: 5  Default: -1
Solving Master
Master solving took 0.03 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Hybrid using IP
No ru

Solution: []
Accuracy:  0.7782777777777777
Best accuracy: 0.7844444444444445
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0

/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/fromnumeric.py:3335: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:217: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:186: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/anaconda3/envs/decisionRule/lib/python3.7/site-packages/numpy/core/_methods.py:209: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


Rule model adding rules took 0.02 seconds
Adding columns took 0.03 seconds
Solving Master
Master solving took 0.05 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Rule generation took 8.75 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 8.76 seconds
Rule model adding rules took 0.01 seconds
Adding columns took 0.02 seconds
Solving Master
Master solving took 0.04 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Rule generation took 6.70 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 6.71 seconds
Rule model adding rules took 0.01 seconds
Adding columns took 0.03 seconds
Time limit for column generation exceeded. Solving MIP.
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Number of solutions returned:  3
S

Accuracy:  0.7835
Solution: []
Accuracy:  0.7791111111111111
Best accuracy: 0.7844444444444445
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

Accuracy:  0.7833333333333333
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7831111111111111
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7828888888888889
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.  0.  0. -0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

Master solving took 0.04 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using IP
Rule generation took 0.46 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 0.48 seconds
Rule model adding rules took 0.00 seconds
Adding columns took 0.00 seconds
Solving Master
Master solving took 0.04 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using IP
Rule generation took 0.26 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 0.27 seconds
Rule model adding rules took 0.00 seconds
Adding columns took 0.00 seconds
Solving Master
Master solving took 0.03 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using IP
Rule generation took 1.88 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 1.

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.02 seconds
Adding columns took 0.04 seconds
Solving Master
Master solving took 0.03 seconds
Starting Rule Generation
Starting row sampling
Row sampling took 0.01 seconds
Starting Rule generation
Hybrid using greedy
Rule generation took 10.01 seconds
Starting Rule selection
Rule selection took 0.00 seconds
Rule generation took 10.02 seconds
Rule model adding rules took 0.04 seconds
Adding columns took 0.08 seconds
Time limit for column generation exceeded. Solving MIP.
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Number of solutions returned:  2
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7865
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.785277777777

   Prev: inf  Min: 0.0  Max: inf  Default: inf
Number of solutions returned:  2
Solution: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0.

Results: (Acc) 0.781 (Time) 11 (Complex) 5 (Cols Gen) 37  (Num Iter) 5
{'accuracy': [0.7807777777777778, 0.7792222222222223, 0.7806666666666666], 'accuracy_train': [0.7804444444444445, 0.781, 0.7804444444444445], 'mip': [[3991.0], [3942.0], [3952.0, 3952.0, 3952.0, 3952.0, 3952.0]], 'mip_final': [3991.0, 3942.0, 3952.0], 'ip': [3952.0, 3942.0, 3952.0], 'complexity': [3.0, 5.0, 5.0], 'eqOfOp': [], 'times': [10.186768344, 11.23492437600001, 10.827548781000004], 'num_iter': [1, 1, 5], 'num_cols_gen': [31, 32, 37], 'hamming': [0.21922222222222223, 0.22077777777777777, 0.21933333333333332], 'hamming_pos': [0.9843355229914098, 0.9869608826479438, 0.9779669504256384], 'hamming_neg': [0.0035607463324312774, 0.0027119611761347415, 0.0029987148364986433], 'hamming_tr': [0.21955555555555556, 0.219, 0.21955555555555556], 'hamming_pos_tr': [0.9766975695314457, 0.9846579476861167, 0.9813742763654669], 'hamming_neg_tr': [0.003854664858305375, 0.0019252709640616087, 0.0037784273187424252], 'hp': 'rule

Best accuracy: 0.7858333333333334
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

Accuracy:  0.7854444444444444
Solution: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0

Accuracy:  0.7792777777777777
Best accuracy: 0.7851666666666667
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 

Accuracy:  0.7793888888888889
Best accuracy: 0.7795555555555556
Selected Rule set: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 1. 0. 0. 0. 0. 0. 0. 

Results: (Acc) 0.780 (Time) 11 (Complex) 21 (Cols Gen) 18  (Num Iter) 1
{'accuracy': [0.7811111111111111, 0.7797777777777778], 'accuracy_train': [0.7795555555555556, 0.7803333333333333], 'mip': [[3991.0, 3968.0], [3955.0]], 'mip_final': [3968.0, 3955.0], 'ip': [3968.0, 3954.0], 'complexity': [9.0, 21.0], 'eqOfOp': [], 'times': [10.80462174600001, 10.863423737999995], 'num_iter': [2, 1], 'num_cols_gen': [17, 18], 'hamming': [0.21888888888888888, 0.22022222222222224], 'hamming_pos': [0.9878726629610914, 0.9879638916750251], 'hamming_neg': [0.0021364477994587666, 0.0017128175849272054], 'hamming_tr': [0.22044444444444444, 0.21966666666666668], 'hamming_pos_tr': [0.9884740666499624, 0.9881790744466801], 'hamming_neg_tr': [0.001641801698907845, 0.001782658300057045], 'hp': 'ruleComplexity', 'hp_val': 30, 'mean_accuracy': 0.7804444444444445, 'std_accuracy': 0.0006666666666666488, 'mean_accuracy_train': 0.7799444444444444, 'std_accuracy_train': 0.00038888888888888307, 'mean_mip_final': 3961.5

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.27 seconds
Adding columns took 0.74 seconds
done
Sorting RC/reset took 1.24 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.02 seconds
Number of solutions returned:  1
Solution: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

init model
adding rules
Rule model adding rules took 0.28 seconds
Adding columns took 0.74 seconds
done
Sorting RC/reset took 1.25 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.02 seconds
Number of solutions returned:  1
Solution: []
Accuracy:  0.7788888888888889
Best accuracy: 0.7788888888888889
Selected Rule set: []
Results: (Acc) 0.778 (Time) 3 (Complex) 0 (Cols Gen) 429  (Num Iter) 0
{'accuracy': [0.778], 'accuracy_train': [0.7788888888888889], 'mip': [[]], 'mip_final': [-1], 'ip': [5970.0], 'complexity': [0.0], 'eqOfOp': [], 'times': [2.5611931130000016], 'num_iter': [0], 'num_cols_gen': [429], 'hamming': [0.222], 'hamming_pos': [1.0], 'hamming_neg': [0.0], 'hamming_tr': [0.22111111111111112], 'hamming_pos_tr': [1.0], 'hamming_neg_tr': [0.0], 'accuracy_True': [0.7471264367816092], 'accuracy_False': [0.7991021324354658], 'eqOp_True': [0.0], 'eqOp_False': [0.0], 'eqOp_True_Train': [0.0], '

Results: (Acc) 0.778 (Time) 2 (Complex) 5 (Cols Gen) 429  (Num Iter) 0
{'accuracy': [0.778], 'accuracy_train': [0.778962962962963], 'mip': [[]], 'mip_final': [-1], 'ip': [5970.0], 'complexity': [5.0], 'eqOfOp': [], 'times': [2.392281151999981], 'num_iter': [0], 'num_cols_gen': [429], 'hamming': [0.222], 'hamming_pos': [1.0], 'hamming_neg': [0.0], 'hamming_tr': [0.22103703703703703], 'hamming_pos_tr': [0.9996649916247906], 'hamming_neg_tr': [0.0], 'accuracy_True': [0.7471264367816092], 'accuracy_False': [0.7991021324354658], 'eqOp_True': [0.0], 'eqOp_False': [0.0], 'eqOp_True_Train': [0.0003898635477582846], 'eqOp_False_Train': [0.0002936857562408223], 'accuracy_True_Train': [0.7597000937207122], 'accuracy_False_Train': [0.7915492957746478], 'hamming_True': [0.25287356321839083], 'hamming_False': [0.20089786756453423], 'hamming_tr_True': [0.2402999062792877], 'hamming_tr_False': [0.2084507042253521], 'hamming_pos_True': [1.0], 'hamming_pos_False': [1.0], 'hamming_pos_tr_True': [0.999610

Accuracy:  0.7829259259259259
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.26 seconds
Adding columns took 0.71 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.18 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [240  50 104 290 110 248 211 246 242  56  66 152 151 198  27 220 340 341
 342 343 344 345 346 347 348 349 350 351 352 353 201 336 335 334 333 222
 223 216 212 210 209 205 218 204 326 327 328 202 330 331 332 203 329 214
 377  11 424 375  46  10 411 387   9   8  51   7   6 399 401 400 415 414
 398 397 296 297 298 306 396 307 402 403 369 405 153 160 161 162 163 164
 165 410 409 408 407 412 427 323 406 404 324 394 395 373 372 355 356 357
 358 359 360 361 362 363 364 365 366 367 371 368 374 325 376 379 370 393
 392 391 390 389 388 386 385 337 338 339 384 383 382 381 380 378 354 413
  18 422 423 425 426 419 416 418 417  19 133  17 420  15  12 421 131 140
 141 142 132   2   1  14 243 30

Accuracy:  0.7788888888888889
Best accuracy: 0.7831481481481481
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.28 seconds
Adding columns took 0.71 seconds
done
Sorting RC/reset took 1.21 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.13 seconds
Number of solutions returned:  3
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7829259259259259
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7831851851851852
Solution: []
Accuracy:  0.7788888888888889
Best accuracy: 0.7831851851851852
Selected Rule set: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Results: (Acc) 0.779 (Time) 3 (Complex) 20 (Cols Gen) 429  (Num Iter) 0
{'accuracy': [0.7793333333333333], 'accuracy_train': [0.7831851851851852], 'mip': [[]], 'mi

Accuracy:  0.788074074074074
Solution: []
Accuracy:  0.7788888888888889
Best accuracy: 0.788074074074074
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. 

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.28 seconds
Adding columns took 0.73 seconds
done
Sorting RC/reset took 1.23 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.24 seconds
Number of solutions returned:  5
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0

Solution: []
Accuracy:  0.7788888888888889
Best accuracy: 0.7893333333333333
Selected Rule set: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.26 seconds
Adding columns took 0.70 seconds
done
Sorting RC/reset took 1.22 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.19 seconds
Number of solutions returned:  3
Solution: [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Accuracy:  0.7912222222222223
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.27 seconds
Adding columns took 0.68 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.14 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [386 368 369 371 372 363 294 385 366 365 397 398 110 422 423 211 221 105
 217 213 219 289 311  59 106  57 239 107  86  88  85 252 308 243  60  70
  26  23 240  49  58  61  68 241 245 247 253  96  84 100  99  93  94 255
 244 249 283  71 276 262  28 248 246 242  65  52  55 293  87  48  50  69
  72  62 104  91  90 284 258 257 102  47  27 118 111 277 266 263 143  21
  89  67 254 238  97 168  66  64  98  54  56 103 313 101 256  95 314 286
 264 287 299 179 122 115  20 113 319 154 120 316 377 327 201 223 222 387
 202 220 203 204 205 399 209 210 424 212 375 216 411 218 332 353 331 333
 334 330 329 335 336 340 341 328 291 342 343 344 345 347 348 349 350 351
 352 326 346 214   7  46  51  5

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.26 seconds
Adding columns took 0.68 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.17 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [385 371 372 311 294 110 386 369 366 398 365 363 422 423 211 397 368 105
  59 221 289 217 213 219  57 239 106 243  70  60  88 107  85 252 240  86
  23  68  61 245 247  58 241  26 308 244 249 283  71  94 100 255  49  93
  99  84 248 242 246 253  96 293 276  62  69  72  28 104  52 257  65  55
  91  90 262  48 284  87  50 258 102 277  27 313  47 118 111  89  21 314
 143  67 238 101  95 256 266 263 103  64  54 286  97  56 254  66 168 264
 299  98 115 122 287 316 319 113 154  20 120 285 274 179 204 375 377 223
 201 222 387 220 399 218 411 202 216 212 424 210 203 209 205 353 346 351
 326 327 328 329 330 331 332 333 334 335 336 340 341 342 343 344 345 347
 348 349 350 352 291 214   6   

Accuracy:  0.790037037037037
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.

Results: (Acc) 0.786 (Time) 3 (Complex) 13 (Cols Gen) 429  (Num Iter) 0
{'accuracy': [0.7863333333333333], 'accuracy_train': [0.790037037037037], 'mip': [[]], 'mip_final': [-1], 'ip': [5696.0], 'complexity': [13.0], 'eqOfOp': [], 'times': [3.2447482809999997], 'num_iter': [0], 'num_cols_gen': [429], 'hamming': [0.21566666666666667], 'hamming_pos': [0.9009009009009009], 'hamming_neg': [0.020137103684661525], 'hamming_tr': [0.21122222222222223], 'hamming_pos_tr': [0.9025125628140703], 'hamming_neg_tr': [0.014978601997146932], 'accuracy_True': [0.7627257799671593], 'accuracy_False': [0.8024691358024691], 'eqOp_True': [0.12337662337662338], 'eqOp_False': [0.0782122905027933], 'eqOp_True_Train': [0.11072124756335283], 'eqOp_False_Train': [0.08751835535976506], 'accuracy_True_Train': [0.7742268041237114], 'accuracy_False_Train': [0.8003674219228414], 'hamming_True': [0.23973727422003285], 'hamming_False': [0.19921436588103256], 'hamming_tr_True': [0.22727272727272727], 'hamming_tr_False': [0

Running CURVE test with parameters: {'ruleGenerator': 'Hybrid', 'masterSolver': 'barrierCrossover', 'numRulesToReturn': 100, 'fairness_module': 'HammingEqOdd', 'group': array([False,  True, False, ...,  True, False, False]), 'epsilon': 0.5, 'ruleComplexity': 10}
HammingEqOdd
Using Hybrid
Using barrier with default crossover
Changed value of parameter Method to 2
   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.24 seconds
Adding columns took 0.67 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.13 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [385 363 365 366 368 369 371 372 110 294 397 398 422 423 211 386 221 105
 217 219 213 289 311  59 106  86  57 107 239 308  88  85 252 243  60  70
  26  23 240  49  96 253  68 241  61 245  58 247  84 100  94 255  99  93
 244 249  71 276 262  28 283  52  87 246 248 242  55  65 293  48  50  90
  91 102 258  62 104  69  72 28

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.26 seconds
Adding columns took 0.66 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.14 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [368 363 365 366 369 371 372 311 294 385 397 398 422 423 211 386 110 105
  59 221 289 217 213 219 239  57 106 243  70  60  88  85 252 107 240  23
  86 247  68  61 241  58 245  26 249 244 283  71 308 100 255  94  49  93
  99  84 242 248 246 293  96 253 276  62  69  72 104  28 257  55  52  65
  90  91 262  48 284  50  87 102 258 277  27 313  47  21 118 111  89 314
 143  67 238  95 256 101 266 263  54  64 103 286  66  56 168  97 264 299
 254  98 115 122 319 316 154  20 120 113 285 274 179 220 399 223 222 377
 375 387 218 424 216 212 353 210 209 205 204 203 202 201 411 352 345 350
 287 326 327 328 329 330 331 332 333 334 335 336 340 341 342 343 344 346
 347 348 349 351 291 214   6   

Accuracy:  0.7892962962962963
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.27 seconds
Adding columns took 0.68 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.14 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [ 59 252  85 363 289 293 294 311 104 365 366 368 369 371 372 385 386 397
 398 110 105 422 423 211  88 243 221 239  60  70 217 106  93 255  94  99
 100  57 240 283 213 219 249 244  86  49  23 107 308  26 245 247 241  71
 257  68  61  58 246 242 248 313  96 253  65  55 276  91  48  50  28  27
  84  52  62  72  69  21 258 238  67 277 102  54  90  64  66  56  47 284
 274 262 299  89 118 143 111 115 122 314 120 264 113 154 319 316 101  95
 305 256 377 327 223 222 387 220 399 218 340 216 326 212 424 210 209 205
 204 203 202 375 411 351 352 341 342 336 335 344 334 333 332 345 331 346
 330 329 347 328 348 349 201 350 353 343 214  63  53   8  11  46   9  10
   7   6  51 123  45 286 116  8

   Prev: -1  Min: -1  Max: 5  Default: -1
init model
adding rules
Rule model adding rules took 0.28 seconds
Adding columns took 0.67 seconds
done
Sorting RC/reset took 1.20 seconds
Solving master IP
Changed value of parameter TimeLimit to 300.0
   Prev: inf  Min: 0.0  Max: inf  Default: inf
Master solving took 0.07 seconds
Number of solutions returned:  2
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.26 seconds
Adding columns took 0.67 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.09 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [294 110 105 311  59 289  57 239 106 243  70  60  88 107 252  85 240  86
  23  61 247 245  58  68 241  26 244 249 283 308  71  94 100 255  49  93
  99  84 242 246 248 253  96 293 104 276  72  62  69  28  52 257  65  55
  91  90  48 284 262  50 258  87 102 277  27 313  21  47  89 111 118 314
 238  67 143 101  95 256  54  64 286 266 263 103  56  66  97 254 168 299
 264  98  20 115 122 287 316 120 211 113 154 319 274 285 179 203 204 119
 216 212 210 223 222 220 218 205 209 214 112 340 341 342 343 344 345 291
 347 348 349 350 351 336 352 375 377 387  11  10   9   8   7   6 399 411
 424 353 335 346 201  53  51  46 334 327 326 329 328 331 332 333 202 330
  63 250  45 170 221 125 206 14

Accuracy:  0.7892962962962963
Solution: [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

   Prev: -1  Min: -1  Max: 5  Default: -1
Adding Rules
Rule model adding rules took 0.27 seconds
Adding columns took 0.71 seconds
Solving relaxed (filter) master
Solving with 429 rules
Master solving took 0.10 seconds
Computing reduced costs
RC took 0.01 seconds
Sorting RC and reset
np.argsort(reduced_costs):  [294 289  59 110 104 293 313 311  23 274 270 105  88 259 252  85 243  60
  70 239 240  57 106  94 255  93 100  99 308 283 244 249  26  71 247 245
 241 107  49 248 242 246  68  58  61 276 257  86  28  84  52  55  65  48
  62  72  69  27  50 277  90 253  96  21 238  91  67  54  64  56  66  47
 256 101  95 258 284 299 262 102 115 264  89 122 118 111 143  45 305 120
 113 319 154 316 211  87 314 123 116 309 250 345 336 353 340 220 352 351
 341 350 349 348 347 342 346 343 344 222 333 223 201 202 203 327 204 205
 209 210 329 212 216 330 331 332 218 326 334 335 328 214   6 375  63  53
  11  51  46 377 387   7   9   8 399  10 411 424 263 301 286 114 279 121
 303 302 112 206 144 221 291 14

KeyboardInterrupt: 

In [ ]:
dataInfo = {
    'file': 'data/compas.csv',
    'groupCol': 'race'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 45,
            'train_limit': 300,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'Default',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'COMPASRaceHEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [5, 15, 30]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [10, 15, 20]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)

In [ ]:
dataInfo = {
    'file': 'data/adult.csv',
    'groupCol': 'gender'
}
globalArgs = {
    'num_splits': 10,
}

tests = []
test_params = {
            'price_limit': 45,
            'train_limit': 300,
            'fixed_model_params': {
                'ruleGenerator': 'Hybrid',
                'masterSolver':'barrierCrossover',
                'numRulesToReturn': 100,
                'fairness_module': 'HammingEqOdd'
            },
            'num_hp_splits': 3,
            'name': 'AdultGenderHEO',
            'hyper_paramaters': {
                'epsilon': [0.02,1],
                'ruleComplexity': [60, 80, 100]
            }
        }
tests.append(test_params)


epsilons = [0, 0.01, 0.05, 0.1, 0.5, 1]
test_complex = [60, 70, 80, 90, 100, 110]
run_fairTest(epsilons, tests, globalArgs, dataInfo, save_rule_set = True, verbose = False, test_complex = test_complex)