In [1]:
import pandas as pd
import numpy as np
import gurobipy as gp
from gurobipy import GRB
from binerizer import *
from DNFRuleModel import DNFRuleModel
from MasterModel import MasterModel
from scipy.stats import bernoulli
from GeneralRuleGenerator import GeneralRuleGenerator

In [2]:
credit = pd.read_csv('data/credit.csv')
data = binerizeData(credit, verbose = False)
X = data.to_numpy()[:,0:164]
Y = data.to_numpy()[:,165]

#X[Y,0] = 1
#X[~Y,0] = 0

ruleMod = DNFRuleModel(X, Y)

In [53]:
np.zeros(X.shape[1])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
mu = np.random.random(sum(Y))
lam = 0
args = {'lam': lam, 'mu': mu}

array([2.87514265e-01, 6.30387075e-01, 8.78960553e-01, 7.31237203e-01,
       6.55350360e-01, 1.78807683e-01, 3.95625841e-01, 8.94078639e-01,
       7.38323958e-01, 6.43399489e-01, 1.44200481e-01, 7.52009968e-01,
       7.62038594e-01, 6.28258087e-01, 3.44379682e-01, 5.40814938e-01,
       9.34015432e-01, 2.71512944e-01, 8.82070450e-01, 1.12574746e-01,
       9.96210258e-01, 9.35575277e-01, 3.62925144e-01, 1.65903271e-01,
       6.16380200e-01, 3.27556515e-01, 5.69603655e-01, 1.83326165e-01,
       6.74878657e-01, 1.39422835e-01, 5.04357609e-02, 1.17249322e-01,
       4.44061578e-01, 7.61121061e-01, 7.54372908e-01, 4.38390254e-01,
       5.01765261e-01, 1.05135464e-01, 3.30110012e-01, 7.21063261e-01,
       1.38682267e-01, 9.65831429e-01, 9.47552281e-01, 6.40973957e-01,
       8.49136752e-01, 2.99486737e-01, 2.27094425e-01, 2.42495873e-01,
       5.77770191e-01, 9.28158186e-01, 9.63444500e-01, 5.98897546e-02,
       3.16854409e-01, 4.55524851e-01, 8.38432103e-01, 2.53442885e-01,
      

In [43]:
np.random.random?

In [15]:
ruleGen = GeneralRuleGenerator(ruleMod,
                               sampler = 'random',
                               ruleGenerator = 'DNF_IP',
                               ruleSelect = 'softmax')
ruleGen.generateRule(args)

(True,
 array([[-0., -0., -0., -0., -0., -0.,  1., -0., -0., -0., -0., -0.,  0.,
         -0., -0.,  1.,  0., -0., -0., -0.,  0.,  0.,  1., -0., -0., -0.,
         -0., -0., -0., -0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
          0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
          0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
          0.,  0.,  1.,  0.,  1.,  0., -0.,  0.,  1.,  1., -0.,  0., -0.,
          0.,  0., -0.,  0.]]))

In [42]:
import time
curr_time = time.time()
time.sleep(1)
time.time() - curr_time

1.0004360675811768